import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // NetLoom Design System - Deep Purple/Cyan Theme
        "surface-container-lowest": "#0c092a",
        "surface-container-low": "#191838",
        "surface-container": "#1d1c3c",
        "surface-container-high": "#282647",
        "surface-container-highest": "#333152",
        "surface-dim": "#110f2f",
        "surface-bright": "#373557",
        "surface-variant": "#333152",
        "surface-tint": "#c7bfff",
        "background": "#110f2f",
        "on-background": "#e3dfff",
        "on-surface": "#e3dfff",
        "on-surface-variant": "#c8c4d8",
        "primary": "#c7bfff",
        "primary-container": "#624af4",
        "primary-fixed": "#e4dfff",
        "primary-fixed-dim": "#c7bfff",
        "on-primary": "#29009f",
        "on-primary-container": "#ebe6ff",
        "on-primary-fixed": "#170065",
        "on-primary-fixed-variant": "#3e15d2",
        "secondary": "#c5c3e5",
        "secondary-container": "#474663",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c5c3e5",
        "on-secondary": "#2e2e49",
        "on-secondary-container": "#b7b5d7",
        "on-secondary-fixed": "#191933",
        "on-secondary-fixed-variant": "#444460",
        "tertiary": "#00FF41",
        "tertiary-container": "#008020",
        "tertiary-fixed": "#90FF90",
        "tertiary-fixed-dim": "#00FF41",
        "on-tertiary": "#003300",
        "on-tertiary-container": "#C0FFC0",
        "on-tertiary-fixed": "#001A00",
        "on-tertiary-fixed-variant": "#004D00",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#928ea1",
        "outline-variant": "#474555",
        "inverse-surface": "#e3dfff",
        "inverse-on-surface": "#2e2d4e",
        "inverse-primary": "#573de9",
        // Legacy shadcn compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
